# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ====================================================================
# Curated dataset – Plan B synthetic tables
# ====================================================================
#
# Synthetic tables generated by scripts/generate_synthetic_curated.py
# and staged in the shared analytics GCS bucket. Regenerate before applying:
#
#   uv run python scripts/generate_synthetic_curated.py
#   terraform apply
#
# All tables are labelled [SYNTHETIC] in their descriptions so stakeholders
# know these are Plan B POC data and not production-validated records.
#
# Toggles (see variables.tf):
#   var.create_curated_tables  – create dataset + empty tables
#   var.load_curated_data      – upload NDJSON and run BigQuery load jobs
#                                (requires create_curated_tables = true and
#                                 the files under data/processed/ to exist)

locals {
  wo_embeddings_local_path         = "${local.repo_root}/data/processed/wo_embeddings.ndjson.gz"
  fct_lead_time_local_path         = "${local.repo_root}/data/processed/fct_lead_time_samples.ndjson.gz"
  dim_focus_components_local_path  = "${local.repo_root}/data/processed/dim_focus_components.ndjson.gz"
  dim_reference_set_local_path     = "${local.repo_root}/data/processed/dim_reference_set.ndjson.gz"

  wo_embeddings_object_name        = "curated/wo_embeddings.ndjson.gz"
  fct_lead_time_object_name        = "curated/fct_lead_time_samples.ndjson.gz"
  dim_focus_components_object_name = "curated/dim_focus_components.ndjson.gz"
  dim_reference_set_object_name    = "curated/dim_reference_set.ndjson.gz"

  create_curated_tables = var.create_curated_tables
  load_curated_data     = var.create_curated_tables && var.load_curated_data
}

resource "google_bigquery_dataset" "curated" {
  count = local.create_curated_tables ? 1 : 0

  project       = var.project_id
  dataset_id    = replace("${var.project_name}_curated", "-", "_")
  friendly_name = "${var.project_name} Curated (Plan B)"
  location      = var.region
  description   = "[SYNTHETIC] Curated tables for PMA online agent POC — Plan B bypass of XML ingest pipeline"

  depends_on = [google_project_service.services]
}

# ====================================================================
# Tables
# ====================================================================

resource "google_bigquery_table" "wo_embeddings" {
  count = local.create_curated_tables ? 1 : 0

  project             = var.project_id
  dataset_id          = google_bigquery_dataset.curated[0].dataset_id
  table_id            = "wo_embeddings"
  description         = "[SYNTHETIC] Workorder embeddings for online retrieval — Plan B POC"
  deletion_protection = false

  schema = file("${path.module}/../shared/wo_embeddings_schema.json")
}

resource "google_bigquery_table" "fct_lead_time_samples" {
  count = local.create_curated_tables ? 1 : 0

  project             = var.project_id
  dataset_id          = google_bigquery_dataset.curated[0].dataset_id
  table_id            = "fct_lead_time_samples"
  description         = "[SYNTHETIC] Lead-time samples per focus component — Plan B POC"
  deletion_protection = false

  schema = file("${path.module}/../shared/fct_lead_time_samples_schema.json")
}

resource "google_bigquery_table" "dim_focus_components" {
  count = local.create_curated_tables ? 1 : 0

  project             = var.project_id
  dataset_id          = google_bigquery_dataset.curated[0].dataset_id
  table_id            = "dim_focus_components"
  description         = "[SYNTHETIC] Focus component dimension for online agent — Plan B POC"
  deletion_protection = false

  schema = file("${path.module}/../shared/dim_focus_components_schema.json")
}

resource "google_bigquery_table" "dim_reference_set" {
  count = local.create_curated_tables ? 1 : 0

  project             = var.project_id
  dataset_id          = google_bigquery_dataset.curated[0].dataset_id
  table_id            = "dim_reference_set"
  description         = "[SYNTHETIC] Reference replacement records per component — Plan B POC"
  deletion_protection = false

  schema = file("${path.module}/../shared/dim_reference_set_schema.json")
}

# ====================================================================
# GCS staging (reuse analytics data bucket)
# ====================================================================

resource "google_storage_bucket_object" "wo_embeddings_ndjson" {
  count = local.load_curated_data ? 1 : 0

  name         = local.wo_embeddings_object_name
  bucket       = google_storage_bucket.analytics_data_bucket.name
  source       = local.wo_embeddings_local_path
  content_type = "application/gzip"
}

resource "google_storage_bucket_object" "fct_lead_time_ndjson" {
  count = local.load_curated_data ? 1 : 0

  name         = local.fct_lead_time_object_name
  bucket       = google_storage_bucket.analytics_data_bucket.name
  source       = local.fct_lead_time_local_path
  content_type = "application/gzip"
}

resource "google_storage_bucket_object" "dim_focus_components_ndjson" {
  count = local.load_curated_data ? 1 : 0

  name         = local.dim_focus_components_object_name
  bucket       = google_storage_bucket.analytics_data_bucket.name
  source       = local.dim_focus_components_local_path
  content_type = "application/gzip"
}

resource "google_storage_bucket_object" "dim_reference_set_ndjson" {
  count = local.load_curated_data ? 1 : 0

  name         = local.dim_reference_set_object_name
  bucket       = google_storage_bucket.analytics_data_bucket.name
  source       = local.dim_reference_set_local_path
  content_type = "application/gzip"
}

# ====================================================================
# BigQuery load jobs
# ====================================================================
#
# job_id embeds filemd5 of the local source: regenerating the data produces
# a new job_id and therefore a real reload on the next terraform apply,
# matching the same pattern used in analytics.tf.

resource "google_bigquery_job" "load_wo_embeddings" {
  count = local.load_curated_data ? 1 : 0

  project  = var.project_id
  job_id   = "load-wo-embeddings-${substr(filemd5(local.wo_embeddings_local_path), 0, 12)}"
  location = var.region

  load {
    source_uris = [
      "gs://${google_storage_bucket.analytics_data_bucket.name}/${local.wo_embeddings_object_name}",
    ]
    destination_table {
      project_id = var.project_id
      dataset_id = google_bigquery_dataset.curated[0].dataset_id
      table_id   = google_bigquery_table.wo_embeddings[0].table_id
    }
    source_format     = "NEWLINE_DELIMITED_JSON"
    write_disposition = "WRITE_TRUNCATE"
    autodetect        = false
  }

  depends_on = [google_storage_bucket_object.wo_embeddings_ndjson]
}

resource "google_bigquery_job" "load_fct_lead_time" {
  count = local.load_curated_data ? 1 : 0

  project  = var.project_id
  job_id   = "load-fct-lead-time-${substr(filemd5(local.fct_lead_time_local_path), 0, 12)}"
  location = var.region

  load {
    source_uris = [
      "gs://${google_storage_bucket.analytics_data_bucket.name}/${local.fct_lead_time_object_name}",
    ]
    destination_table {
      project_id = var.project_id
      dataset_id = google_bigquery_dataset.curated[0].dataset_id
      table_id   = google_bigquery_table.fct_lead_time_samples[0].table_id
    }
    source_format     = "NEWLINE_DELIMITED_JSON"
    write_disposition = "WRITE_TRUNCATE"
    autodetect        = false
  }

  depends_on = [google_storage_bucket_object.fct_lead_time_ndjson]
}

resource "google_bigquery_job" "load_dim_focus_components" {
  count = local.load_curated_data ? 1 : 0

  project  = var.project_id
  job_id   = "load-dim-focus-${substr(filemd5(local.dim_focus_components_local_path), 0, 12)}"
  location = var.region

  load {
    source_uris = [
      "gs://${google_storage_bucket.analytics_data_bucket.name}/${local.dim_focus_components_object_name}",
    ]
    destination_table {
      project_id = var.project_id
      dataset_id = google_bigquery_dataset.curated[0].dataset_id
      table_id   = google_bigquery_table.dim_focus_components[0].table_id
    }
    source_format     = "NEWLINE_DELIMITED_JSON"
    write_disposition = "WRITE_TRUNCATE"
    autodetect        = false
  }

  depends_on = [google_storage_bucket_object.dim_focus_components_ndjson]
}

resource "google_bigquery_job" "load_dim_reference_set" {
  count = local.load_curated_data ? 1 : 0

  project  = var.project_id
  job_id   = "load-dim-reference-${substr(filemd5(local.dim_reference_set_local_path), 0, 12)}"
  location = var.region

  load {
    source_uris = [
      "gs://${google_storage_bucket.analytics_data_bucket.name}/${local.dim_reference_set_object_name}",
    ]
    destination_table {
      project_id = var.project_id
      dataset_id = google_bigquery_dataset.curated[0].dataset_id
      table_id   = google_bigquery_table.dim_reference_set[0].table_id
    }
    source_format     = "NEWLINE_DELIMITED_JSON"
    write_disposition = "WRITE_TRUNCATE"
    autodetect        = false
  }

  depends_on = [google_storage_bucket_object.dim_reference_set_ndjson]
}
